<?php

declare(strict_types=1);

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;

/**
 * Regenerates the generated parts of the AI context (DEC-031):
 *  - .ai/knowledge/db/*.md   schema cards per table-prefix group, from information_schema
 *  - .ai/state/bugs-index.md open bugs from docs/refactor/known-bugs-report.md's summary table
 *  - .claude/rules/**        copy of .ai/rules/** (Claude Code loads rules from there by path)
 */
class RefreshAiContext extends Command
{
    protected $signature = 'ai:refresh-context {--only= : schema, bugs or rules}';

    protected $description = 'Regenerate AI schema cards, the open-bugs index and the .claude/rules copy';

    /** Table-name prefix => card file. First match wins, so longer prefixes come first. */
    private const GROUPS = [
        'xlr8_vehicle_pricing_' => 'vehicle-pricing',
        'xlr8_vehicle_' => 'vehicle',
        'xlr8_admin_' => 'admin-org',
        'xlr8_iam_' => 'iam',
        'xlr8_crm_' => 'crm',
        'xlr8_cre_' => 'crm',
        'xlr8_finexch_' => 'crm',
        'xlr8_booking_' => 'booking',
        'xlr8_financer_' => 'booking',
        'xlr8_spare_' => 'spares',
        'xlr8_utils_' => 'utils',
        'xlr8_system_' => 'system',
    ];

    public function handle(): int
    {
        $only = $this->option('only');

        if (! $only || $only === 'schema') {
            $this->schemaCards();
        }
        if (! $only || $only === 'bugs') {
            $this->bugsIndex();
        }
        if (! $only || $only === 'rules') {
            $this->syncRules();
        }

        return self::SUCCESS;
    }

    private function schemaCards(): void
    {
        $db = DB::connection()->getDatabaseName();
        $models = $this->modelTableMap();

        $tables = DB::select(
            'SELECT table_name AS name, table_rows AS approx_rows, table_collation AS coll
             FROM information_schema.tables WHERE table_schema = ? AND table_type = "BASE TABLE" ORDER BY table_name',
            [$db]
        );
        $columns = collect(DB::select(
            'SELECT table_name AS t, column_name AS c, column_type AS type, is_nullable AS nullable, column_key AS k
             FROM information_schema.columns WHERE table_schema = ? ORDER BY table_name, ordinal_position',
            [$db]
        ))->groupBy('t');
        $indexes = collect(DB::select(
            'SELECT table_name AS t, index_name AS i, non_unique AS nu, GROUP_CONCAT(column_name ORDER BY seq_in_index) AS cols
             FROM information_schema.statistics WHERE table_schema = ? GROUP BY table_name, index_name, non_unique',
            [$db]
        ))->groupBy('t');

        $cards = [];
        foreach ($tables as $table) {
            $group = 'other';
            foreach (self::GROUPS as $prefix => $card) {
                if (str_starts_with($table->name, $prefix)) {
                    $group = $card;
                    break;
                }
            }
            $cards[$group][] = $table;
        }

        $dir = base_path('.ai/knowledge/db');
        File::ensureDirectoryExists($dir);
        File::cleanDirectory($dir);

        $index = ['# Database schema cards (generated by `php artisan ai:refresh-context` — do not edit)', '',
            "Database `{$db}`, generated ".now()->format('d-m-Y H:i').'. Row counts are InnoDB estimates.', '',
            '| Card | Tables |', '|---|---|'];

        foreach ($cards as $group => $groupTables) {
            $lines = ["# {$group} tables (generated — do not edit)", ''];
            foreach ($groupTables as $table) {
                $model = $models[$table->name] ?? '—';
                $lines[] = "## `{$table->name}` · ~{$table->approx_rows} rows · model: {$model}";
                $cols = ($columns[$table->name] ?? collect())
                    ->map(fn ($c) => $c->c.' '.$c->type.($c->nullable === 'YES' ? '?' : '').($c->k === 'PRI' ? ' PK' : ''))
                    ->implode(', ');
                $lines[] = $cols;
                $idx = ($indexes[$table->name] ?? collect())
                    ->reject(fn ($i) => $i->i === 'PRIMARY')
                    ->map(fn ($i) => ($i->nu ? '' : 'UNIQUE ').'('.$i->cols.')')
                    ->implode(', ');
                if ($idx !== '') {
                    $lines[] = "Indexes: {$idx}";
                }
                $lines[] = '';
            }
            File::put("{$dir}/{$group}.md", implode("\n", $lines));
            $index[] = "| [{$group}]({$group}.md) | ".count($groupTables).' |';
        }

        File::put("{$dir}/index.md", implode("\n", $index)."\n");
        $this->info('Schema cards: '.count($tables).' tables in '.count($cards).' cards.');
    }

    /** Scans app/Models for explicit $table declarations. */
    private function modelTableMap(): array
    {
        $map = [];
        foreach (File::allFiles(app_path('Models')) as $file) {
            $src = $file->getContents();
            if (preg_match('/protected\s+\$table\s*=\s*[\'"]([^\'"]+)[\'"]/', $src, $t)
                && preg_match('/^namespace\s+([^;]+);/m', $src, $ns)
                && preg_match('/^class\s+(\w+)/m', $src, $cl)) {
                $map[$t[1]] = isset($map[$t[1]]) ? $map[$t[1]].', '.$cl[1] : $ns[1].'\\'.$cl[1];
            }
        }

        return $map;
    }

    private function bugsIndex(): void
    {
        $report = base_path('docs/refactor/known-bugs-report.md');
        if (! File::exists($report)) {
            $this->warn('known-bugs-report.md not found; skipped bugs index.');

            return;
        }

        $open = [];
        foreach (explode("\n", File::get($report)) as $line) {
            if (! preg_match('/^\| (BUG-\d{3}) \|/', $line, $m)) {
                continue;
            }
            $cells = array_map('trim', explode('|', $line));
            $n = count($cells);
            // | id | title | severity | status | found | fixed |
            $status = $cells[$n - 4] ?? '';
            if (preg_match('/^FIXED\b/i', $status) || preg_match("/^WON'T FIX/i", $status)) {
                continue;
            }
            $title = mb_strimwidth(implode('|', array_slice($cells, 2, $n - 7)), 0, 160, '…');
            $open[] = "| {$m[1]} | {$cells[$n - 5]} | ".mb_strimwidth($status, 0, 40, '…')." | {$title} |";
        }

        $out = ['# Open bugs index (generated by `php artisan ai:refresh-context` — do not edit)', '',
            'Full entries: grep `### BUG-NNN` in `docs/refactor/known-bugs-report.md`. Generated '.now()->format('d-m-Y H:i').'.', '',
            '| Bug | Severity | Status | Title |', '|---|---|---|---|', ...$open];
        File::ensureDirectoryExists(base_path('.ai/state'));
        File::put(base_path('.ai/state/bugs-index.md'), implode("\n", $out)."\n");
        $this->info('Bugs index: '.count($open).' open.');
    }

    private function syncRules(): void
    {
        $from = base_path('.ai/rules');
        $to = base_path('.claude/rules');
        File::ensureDirectoryExists($to);
        File::cleanDirectory($to);
        File::copyDirectory($from, $to);
        File::put("{$to}/README.md", "Generated copy of `.ai/rules` (php artisan ai:refresh-context). Edit `.ai/rules`, not this folder.\n");
        $this->info('Rules synced to .claude/rules.');
    }
}
